name: laravel

services:
  laravel:
    image: boilerplate
    container_name: laravel-app
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - "./data/storage:/var/www/laravel/storage"
      - "./logs:/var/www/laravel/storage/logs"
      - "./www-root/:/var/www/laravel/"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mariadb
    container_name: laravel-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
